apiVersion: v1
kind: Namespace
metadata:
  name: subnetavailableipcount-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subnetavailableipcount-sa
  namespace: subnetavailableipcount-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::871386769552:role/demo-robertom-us-west-2-subnetavailableipcount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subnetavailableipcount-app
  labels:
    app: subnetavailableipcount-app
  namespace: subnetavailableipcount-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subnetavailableipcount-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9000"
      labels:
        app: subnetavailableipcount-app
    spec:
      serviceAccountName: subnetavailableipcount-sa
      containers:
        - name: subnetavailableipcount-app
          image: 871386769552.dkr.ecr.us-east-1.amazonaws.com/gdrs/prom-aws-subnets-exporter:latest
          env:
#          - name: AWS_REGION
#            value: "us-west-2"
          - name: AWS_VPC_ID
            value: "vpc-faf77d9d"
---